#language: shell

#Enable modern build platform, not container based.
sudo: required
dist: trusty

# Apparently caching is disabled, since we used modern build platform as we require clamav and sudo ;/
# caching the /var/lib/clamav/ will save +/-9mins of run time and allow the use of freshclam signatures

#Enable Caching
#cache:
#  directories:
#    - tmp/cache

before_install:
  - "sudo apt-get update -y -qq"
  - "sudo apt-get install mysql-server -y -qq"
  - "sudo service mysql restart"
  #- "sudo apt-get install pdns-server pdns-backend-mysql -y -qq"
  - "sudo apt-get install gdnsd -y -qq"
  #- "sudo service gdnsd start"

install:
  - "sudo mkdir -p /etc/powerdns/pdns.d"
  - "sudo cp -f .travis/tests/powerdns/gmysql.conf /etc/powerdns/pdns.d/pdns.local.gmysql.conf"
  - "sudo sh -e .travis/ci-setup.sh"


script:
  - "sudo sh -e .travis/ci-test.sh"

#addons:
#  code_climate:
#    repo_token: 