#language: shell

#Enable modern build platform, not container based.
sudo: required
dist: trusty

# Apparently caching is disabled, since we used modern build platform as we require clamav and sudo ;/
# caching the /var/lib/clamav/ will save +/-9mins of run time and allow the use of freshclam signatures

#Enable Caching
#cache:
#  directories:
#    - tmp/cache

before_install:
  - "sudo apt-get -qq update"
  - "sudo apt-get install -y mysql-server"
  - "sudo service mysql restart"
  - "sudo cp -f /sbin/start /sbin/start.backup"
  - "sudo cp -f .travis/tests/gdnsd/workaround_failed_start_to_install.sh /sbin/start"
  - "sudo chmod +x /sbin/start"
  - "sudo apt-get install -y -f gdnsd libev4 liburcu1"
  - "sudo cp -f /sbin/start.backup /sbin/start"
  #- sudo apt-get update -q
  #- "sudo service gdnsd start"

install:
  - "sudo mkdir -p /etc/powerdns/pdns.d"
  - "sudo cp -f .travis/tests/powerdns/gmysql.conf /etc/powerdns/pdns.d/pdns.local.gmysql.conf"
  - "sudo sh -e .travis/ci-setup.sh"


script:
  - "sudo sh -e .travis/ci-test.sh"

#addons:
#  code_climate:
#    repo_token: 