#language: shell

#Enable modern build platform, not container based.
sudo: required
dist: trusty

# Apparently caching is disabled, since we used modern build platform
#Enable Caching
#cache:
#  directories:
#    - tmp/cache

before_install:
  - "sudo apt-get -qq update"
  - "sudo apt-get install -y mysql-server"
  - "sudo service mysql restart"
  # Begin: workaround for failed start of gdnsd
  - "echo exit 101 | sudo tee /usr/sbin/policy-rc.d"
  - "sudo chmod +x /usr/sbin/policy-rc.d"
  # End: workaround for failed start of gdnsd
  - "sudo apt-get install -y -f gdnsd libev4 liburcu1"


install:
  - "sudo sh -e .travis/ci-setup.sh"
  - "sudo mkdir -p /etc/powerdns/pdns.d"
  - "sudo cp -f .travis/tests/powerdns/gmysql.conf /etc/powerdns/pdns.d/pdns.local.gmysql.conf"

script:
  - "sudo sh -e .travis/ci-test.sh"

#addons:
#  code_climate:
#    repo_token: 